/**
 * Copies the engine's built chunks into a generated TypeScript module.
 *
 * The `/embed.js` route assembles a response by concatenating core with the one
 * style and one effect a visitor asked for. Reading those from disk at request
 * time would tie the route to a Node filesystem; inlining them as strings keeps
 * it deployable to an edge runtime, where this route belongs.
 *
 * Runs from `predev` and `prebuild`, so the generated file is never stale.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.join(here, '..');
const dist = path.join(web, '..', '..', 'packages', 'engine', 'dist');

const exists = async (p) => {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
};

/**
 * `npm run engine` and this script are separate OS processes: the engine build
 * writes its report only after every dist file lands, so a plain existence
 * check right after that process exits should always pass. On at least one
 * hosted build runner it did not — `core.js` and `dist/m/*.js` were visible but
 * `embed.js`, written in the same batch, was not yet, for a window of a few
 * hundred ms. Rather than depend on the two processes' filesystem views
 * syncing up instantly, wait for it.
 */
async function waitFor(p, { tries = 20, delayMs = 150 } = {}) {
  for (let i = 0; i < tries; i++) {
    if (await exists(p)) return;
    await new Promise((r) => setTimeout(r, delayMs));
  }
}

await waitFor(path.join(dist, 'core.js'));
if (!(await exists(path.join(dist, 'core.js')))) {
  console.error(
    '\n  Engine not built. Run `npm run engine` from the repo root first.\n',
  );
  process.exit(1);
}

const core = await fs.readFile(path.join(dist, 'core.js'), 'utf8');
const chunkDir = path.join(dist, 'm');
const files = await fs.readdir(chunkDir);

const styles = {};
const effects = {};
const hovers = {};

for (const file of files) {
  if (!file.endsWith('.js')) continue;
  const code = await fs.readFile(path.join(chunkDir, file), 'utf8');
  const id = file.slice(2, -3);
  if (file.startsWith('s-')) styles[id] = code;
  else if (file.startsWith('e-')) effects[id] = code;
  else if (file.startsWith('h-')) hovers[id] = code;
}

const out = `// GENERATED by scripts/collect-embed.mjs — do not edit.
// Source: packages/engine/dist. Regenerate with \`npm run engine\`.
/* eslint-disable */

export const CORE: string = ${JSON.stringify(core)};

export const STYLE_CHUNKS: Record<string, string> = ${JSON.stringify(styles)};

export const EFFECT_CHUNKS: Record<string, string> = ${JSON.stringify(effects)};

export const HOVER_CHUNKS: Record<string, string> = ${JSON.stringify(hovers)};
`;

await fs.writeFile(path.join(web, 'lib', 'embed-assets.generated.ts'), out);

// Two static bundles alongside the assembled route: the whole library, for
// anyone switching styles at runtime, and the embeddable builder dashboard.
await waitFor(path.join(dist, 'embed.js'));
await waitFor(path.join(dist, 'dashboard.js'));
await fs.copyFile(path.join(dist, 'embed.js'), path.join(web, 'public', 'embed.full.js'));
await fs.copyFile(path.join(dist, 'dashboard.js'), path.join(web, 'public', 'dashboard.js'));

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + 'kb';
console.log(
  `  embed assets: core ${kb(core)} raw, ${Object.keys(styles).length} styles, ` +
    `${Object.keys(effects).length} effects, ${Object.keys(hovers).length} hover transforms`,
);
