/**
 * Builds the engine, then copies its output into this workspace.
 *
 * This used to assume `packages/engine/dist` was already fresh, built moments
 * earlier by a separate `npm run engine` invocation that the root `build`
 * script chained before this one. That works everywhere it was tried except
 * one hosted build runner, where `embed.js` was reproducibly still ENOENT
 * here — even after polling for several seconds — despite the engine build's
 * own process having just finished reading that same file back to report its
 * size. Whatever the cause, it lived at the boundary between two independent
 * npm-script processes trusting each other's filesystem state.
 *
 * So that boundary is gone. This script spawns the engine build itself and
 * awaits its real exit code before touching `dist/` — the only guarantee this
 * needed was "the process that wrote these files has fully exited before I
 * read them," and a direct parent/child relationship is the one way to have
 * that guarantee unconditionally, on any infrastructure.
 *
 * Runs from `predev` and `prebuild`, so the generated file is never stale.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.join(here, '..');
const engineDir = path.join(web, '..', '..', 'packages', 'engine');
const dist = path.join(engineDir, 'dist');

function runEngineBuild() {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, ['build.mjs'], { cwd: engineDir, stdio: 'inherit' });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`engine build exited with code ${code}`));
    });
  });
}

try {
  await runEngineBuild();
} catch (err) {
  console.error(`\n  Engine build failed: ${err.message}\n`);
  process.exit(1);
}

const exists = async (p) => {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
};

if (!(await exists(path.join(dist, 'core.js')))) {
  const seen = await fs.readdir(dist).catch(() => []);
  console.error(
    `\n  Engine build reported success but ${path.join(dist, 'core.js')} is missing.\n` +
      `  dist/ contains: ${seen.join(', ') || '(empty)'}\n`,
  );
  process.exit(1);
}

const core = await fs.readFile(path.join(dist, 'core.js'), 'utf8');
const chunkDir = path.join(dist, 'm');
const files = await fs.readdir(chunkDir);

const styles = {};
const effects = {};
const hovers = {};

for (const file of files) {
  if (!file.endsWith('.js')) continue;
  const code = await fs.readFile(path.join(chunkDir, file), 'utf8');
  const id = file.slice(2, -3);
  if (file.startsWith('s-')) styles[id] = code;
  else if (file.startsWith('e-')) effects[id] = code;
  else if (file.startsWith('h-')) hovers[id] = code;
}

const out = `// GENERATED by scripts/collect-embed.mjs — do not edit.
// Source: packages/engine/dist. Regenerate with \`npm run engine\`.
/* eslint-disable */

export const CORE: string = ${JSON.stringify(core)};

export const STYLE_CHUNKS: Record<string, string> = ${JSON.stringify(styles)};

export const EFFECT_CHUNKS: Record<string, string> = ${JSON.stringify(effects)};

export const HOVER_CHUNKS: Record<string, string> = ${JSON.stringify(hovers)};
`;

await fs.writeFile(path.join(web, 'lib', 'embed-assets.generated.ts'), out);

// Two static bundles alongside the assembled route: the whole library, for
// anyone switching styles at runtime, and the embeddable builder dashboard.
//
// Every file `public/` ever holds — embed.js, embed.full.js, dashboard.js,
// the m/ chunk mirror — is generated at build time and therefore gitignored.
// Git does not track empty directories, so on a fresh clone `public/` does
// not exist at all until something creates it; it only ever seemed to on a
// dev machine because a previous build had already made it once and it was
// never deleted. `fs.writeFile` does not create parent directories, so this
// is required before either write below, not optional.
//
// (This is also, in hindsight, almost certainly what the earlier `fs.copyFile`
// ENOENT was too — copyFile's error object names the *source* path regardless
// of which side actually failed, which pointed the previous investigation at
// the wrong file. Read+write leaves nothing ambiguous the next time.)
await fs.mkdir(path.join(web, 'public'), { recursive: true });

async function copyFileContents(src, dest) {
  await fs.writeFile(dest, await fs.readFile(src));
}
await copyFileContents(path.join(dist, 'embed.js'), path.join(web, 'public', 'embed.full.js'));
await copyFileContents(path.join(dist, 'dashboard.js'), path.join(web, 'public', 'dashboard.js'));

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + 'kb';
console.log(
  `  embed assets: core ${kb(core)} raw, ${Object.keys(styles).length} styles, ` +
    `${Object.keys(effects).length} effects, ${Object.keys(hovers).length} hover transforms`,
);
